<a href="https://colab.research.google.com/github/Skvorok/netology_pyda/blob/master/Hw9_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Домашнее задание

Задание 1
Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [3]:
import numpy as np
N = 10
variable = np.array(N)
variable_1 = list(reversed(range(N)))
np.array(variable_1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [11]:
variable = np.diag(list(reversed(range(N))))
print(variable)
print(f'Сумма диагонали: {np.trace(variable)}')


[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма диагонали: 45


Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [13]:
from scipy import linalg
a = np.array([[4,2,1],
              [1,3,0],
              [0,5,4]])
b = np.array([4,12,-3])
v = linalg.solve(a,b)
print(f'x = {v[0]}, y = {v[1]}, z = {v[2]}')

x = 0.4666666666666668, y = 3.844444444444444, z = -5.555555555555555
